In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://liquipedia.net/pubgmobile/PUBG_Mobile_Global_Open/2026/Season_1/Statistics/Teams"
headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"}

response = requests.get(url, headers=headers)
print(response.status_code)

soup = BeautifulSoup(response.text, "html.parser")
tables = soup.find_all("table")
print(f"Found {len(tables)} tables")

403
Found 0 tables

In [3]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://liquipedia.net/pubgmobile/PUBG_Mobile_Global_Open/2026/Season_1/Statistics/Teams"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.5",
    "Referer": "https://liquipedia.net/",
}

response = requests.get(url, headers=headers)
print(response.status_code)

soup = BeautifulSoup(response.text, "html.parser")
tables = soup.find_all("table")
print(f"Found {len(tables)} tables")

403
Found 0 tables

In [8]:
import pandas as pd

df = pd.read_csv('../data/team_standings.csv')
print(df.shape)
df.head()

(16, 28)

,Rank,Participant,Total Points,MPe Game,Game 1 P,Game 1 K,Game 2 P,Game 2 K,Game 3 P,Game 3 K,...,Game 8 P,Game 8 K,Game 9 P,Game 9 K,Game 10 P,Game 10 K,Game 11 P,Game 11 K,Game 12 P,Game 12 K
0,1st,4Thrives,122,Game 8,10th,2,1st,9,3rd,8,...,14th,5,8th,1,13th,3,9th,1,3rd,4
1,2nd,ULF Esports,104,Game 11,3rd,5,7th,5,1st,13,...,6th,3,2nd,17,4th,16,5th,2,9th,0
2,3rd,FURIA,97,NaN,1st,16,8th,10,12th,0,...,9th,3,1st,11,7th,0,13th,3,2nd,13
3,4th,S2G Esports,83,NaN,14th,0,15th,0,2nd,3,...,4th,5,16th,0,9th,2,1st,17,6th,7
4,5th,eArena,83,NaN,11th,4,2nd,6,6th,8,...,1st,12,5th,6,8th,0,3rd,5,15th,1

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 28 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16 non-null     str
 1   Participant   16 non-null     str
 2   Total Points  16 non-null     int64
 3   MPe Game      2 non-null      str
 4   Game 1 P      16 non-null     str
 5   Game 1 K      16 non-null     int64
 6   Game 2 P      16 non-null     str
 7   Game 2 K      16 non-null     int64
 8   Game 3 P      16 non-null     str
 9   Game 3 K      16 non-null     int64
 10  Game 4 P      16 non-null     str
 11  Game 4 K      16 non-null     int64
 12  Game 5 P      16 non-null     str
 13  Game 5 K      16 non-null     int64
 14  Game 6 P      16 non-null     str
 15  Game 6 K      16 non-null     int64
 16  Game 7 P      16 non-null     str
 17  Game 7 K      16 non-null     int64
 18  Game 8 P      16 non-null     str
 19  Game 8 K      16 non-null     int64
 20  Game 9 P      16 non-null     str
 21  Game 9 K      16 non-null     int64
 22  Game 10 P     16 non-null     str
 23  Game 10 K     16 non-null     int64
 24  Game 11 P     16 non-null     str
 25  Game 11 K     16 non-null     int64
 26  Game 12 P     16 non-null     str
 27  Game 12 K     16 non-null     int64
dtypes: int64(13), str(15)
memory usage: 4.5 KB

In [12]:
df[['Game 1 P', 'Game 2 P', 'Game 3 P']].head(10)

  Game 1 P Game 2 P Game 3 P
0     10th      1st      3rd
1      3rd      7th      1st
2      1st      8th     12th
3     14th     15th      2nd
4     11th      2nd      6th
5     12th     16th     15th
6      5th      6th      5th
7     16th     13th     10th
8      6th     10th      9th
9      9th      5th      7th

In [14]:
df['Rank'].head(10)

0     1st
1     2nd
2     3rd
3     4th
4     5th
5     6th
6     7th
7     8th
8     9th
9    10th
Name: Rank, dtype: str

In [16]:
import re

def clean_rank(value):
    if pd.isna(value):
        return None
    return int(re.sub(r'(st|nd|rd|th)$', '', str(value).strip()))

# Clean the overall Rank column
df['Rank'] = df['Rank'].apply(clean_rank)

# Clean every "Game X P" column
placement_cols = [col for col in df.columns if col.endswith(' P')]
for col in placement_cols:
    df[col] = df[col].apply(clean_rank)

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 28 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16 non-null     int64
 1   Participant   16 non-null     str
 2   Total Points  16 non-null     int64
 3   MPe Game      2 non-null      str
 4   Game 1 P      16 non-null     int64
 5   Game 1 K      16 non-null     int64
 6   Game 2 P      16 non-null     int64
 7   Game 2 K      16 non-null     int64
 8   Game 3 P      16 non-null     int64
 9   Game 3 K      16 non-null     int64
 10  Game 4 P      16 non-null     int64
 11  Game 4 K      16 non-null     int64
 12  Game 5 P      16 non-null     int64
 13  Game 5 K      16 non-null     int64
 14  Game 6 P      16 non-null     int64
 15  Game 6 K      16 non-null     int64
 16  Game 7 P      16 non-null     int64
 17  Game 7 K      16 non-null     int64
 18  Game 8 P      16 non-null     int64
 19  Game 8 K      16 non-null     int64
 20  Game 9 P      16 non-null     int64
 21  Game 9 K      16 non-null     int64
 22  Game 10 P     16 non-null     int64
 23  Game 10 K     16 non-null     int64
 24  Game 11 P     16 non-null     int64
 25  Game 11 K     16 non-null     int64
 26  Game 12 P     16 non-null     int64
 27  Game 12 K     16 non-null     int64
dtypes: int64(26), str(2)
memory usage: 3.8 KB

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 28 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16 non-null     int64
 1   Participant   16 non-null     str
 2   Total Points  16 non-null     int64
 3   MPe Game      2 non-null      str
 4   Game 1 P      16 non-null     int64
 5   Game 1 K      16 non-null     int64
 6   Game 2 P      16 non-null     int64
 7   Game 2 K      16 non-null     int64
 8   Game 3 P      16 non-null     int64
 9   Game 3 K      16 non-null     int64
 10  Game 4 P      16 non-null     int64
 11  Game 4 K      16 non-null     int64
 12  Game 5 P      16 non-null     int64
 13  Game 5 K      16 non-null     int64
 14  Game 6 P      16 non-null     int64
 15  Game 6 K      16 non-null     int64
 16  Game 7 P      16 non-null     int64
 17  Game 7 K      16 non-null     int64
 18  Game 8 P      16 non-null     int64
 19  Game 8 K      16 non-null     int64
 20  Game 9 P      16 non-null     int64
 21  Game 9 K      16 non-null     int64
 22  Game 10 P     16 non-null     int64
 23  Game 10 K     16 non-null     int64
 24  Game 11 P     16 non-null     int64
 25  Game 11 K     16 non-null     int64
 26  Game 12 P     16 non-null     int64
 27  Game 12 K     16 non-null     int64
dtypes: int64(26), str(2)
memory usage: 3.8 KB

In [20]:
kill_cols = [col for col in df.columns if col.endswith(' K')]
df['Total Kill Points'] = df[kill_cols].sum(axis=1)
df['Total Placement Points'] = df['Total Points'] - df['Total Kill Points']

df[['Participant', 'Total Points', 'Total Kill Points', 'Total Placement Points']].sort_values('Total Points', ascending=False)

      Participant  Total Points  Total Kill Points  Total Placement Points
0        4Thrives           122                 77                      45
1     ULF Esports           104                 70                      34
2           FURIA            97                 65                      32
3     S2G Esports            83                 53                      30
4          eArena            83                 56                      27
5      TT Project            77                 51                      26
6       GOAT Team            75                 49                      26
7          Aurora            73                 47                      26
8    BOOM Esports            71                 49                      22
9      Team Flash            69                 45                      24
10   Gaming Stars            59                 42                      17
11  Horaa Esports            59                 49                      10
12         Geekay            54                 30                      24
13       Bigetron            53                 40                      13
14    721 Esports            51                 36                      15
15         Pandum            30                 17                      13

In [21]:
df.to_csv('../data/team_standings_clean.csv', index=False)
print("Saved!")

Saved!